"use client";
import dynamic from "next/dynamic";
import { useEffect, useState } from "react";

const HazardMap = dynamic(() => import("../components/HazardMap"), { ssr: false });

const REGION = "pilot-odisha-puri";
const LANGS = [["en", "English"], ["hi", "हिन्दी"], ["bn", "বাংলা"], ["or", "ଓଡ଼ିଆ"]];

async function api(url, body) {
  const r = await fetch(url, body ? { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) } : {});
  if (!r.ok) throw new Error(`${r.status} ${(await r.text()).slice(0, 160)}`);
  return r.json();
}

export default function Page() {
  const [data, setData] = useState(null);
  const [err, setErr] = useState("");
  const [lang, setLang] = useState("en");
  const [adv, setAdv] = useState(null);
  const [advErr, setAdvErr] = useState("");
  const [busy, setBusy] = useState(false);
  const [chan, setChan] = useState("sms_mock");
  const [rcpt, setRcpt] = useState("");
  const [sent, setSent] = useState("");

  useEffect(() => {
    Promise.all([api(`/api/regions/${REGION}/hazard-layers`), api(`/api/regions/${REGION}/summary`)])
      .then(([h, s]) => setData({ h, s }))
      .catch((e) => setErr(e.message));
  }, []);

  const s = data?.s, st = s?.summary_stats;

  async function generate() {
    setBusy(true); setAdvErr(""); setAdv(null); setSent("");
    try {
      setAdv(await api("/api/advisory/generate", { region_id: REGION, cyclone_id: s.cyclone_id, language: lang }));
    } catch (e) { setAdvErr(e.message); }
    setBusy(false);
  }

  async function dispatch() {
    try {
      const r = await api("/api/alerts/dispatch", { region_id: REGION, cyclone_id: s.cyclone_id, channel: chan, advisory: adv, recipient: rcpt.trim() || null });
      setSent(r.detail);
    } catch (e) { setSent("Dispatch failed: " + e.message); }
  }

  return (
    <div className="app">
      <aside>
        <h1>Cyclone Early Warning</h1>
        <p className="sub">
          {err ? <span className="err">Could not load data: {err} (is the API running on port 8000?)</span>
            : s ? `${s.region_id} · cyclone ${s.cyclone_id}` : "Loading region…"}
        </p>

        <div className="stats">
          <div className="stat"><b>{st?.max_surge_height_m ?? "–"}</b><span>Peak surge (m)</span></div>
          <div className="stat"><b>{st?.max_flood_depth_m ?? "–"}</b><span>Flood depth (m)</span></div>
          <div className="stat"><b>{st?.mean_exposure_score ?? "–"}</b><span>Mean exposure</span></div>
        </div>
        <div className="legend">
          {["critical", "high", "medium", "low"].map((k) => (
            <span key={k}><i style={{ background: `var(--${k})` }} />{k[0].toUpperCase() + k.slice(1)}</span>
          ))}
        </div>
        {s?.bulletin_text && <p className="bulletin">{s.bulletin_text}</p>}

        <h2>Most exposed</h2>
        <ul>{(st?.affected_areas?.length ? st.affected_areas : ["None flagged"]).map((a) => <li key={a}>{a}</li>)}</ul>

        <h2>Advisory</h2>
        <div className="row">
          <select value={lang} onChange={(e) => setLang(e.target.value)} aria-label="Language">
            {LANGS.map(([v, n]) => <option key={v} value={v}>{n}</option>)}
          </select>
          <button onClick={generate} disabled={busy || !s}>{busy ? "Generating…" : "Generate advisory"}</button>
        </div>
        {advErr && <p className="err">{advErr}</p>}
        {adv && (
          <div>
            <p><span className={`badge sev-${adv.severity}`}>{adv.severity}</span></p>
            <p>{adv.advisory_text}</p>
            <b>Affected areas</b>
            <ul>{adv.affected_areas.map((x) => <li key={x}>{x}</li>)}</ul>
            <b>Recommended actions</b>
            <ul>{adv.recommended_actions.map((x) => <li key={x}>{x}</li>)}</ul>
            <p className="note">{adv.is_fallback ? "Fallback advisory (Gemini not reached — check GEMINI_API_KEY)." : `Generated by ${adv.model_used}`}</p>
          </div>
        )}

        <h2>Dispatch alert</h2>
        <div className="row">
          <select value={chan} onChange={(e) => setChan(e.target.value)} aria-label="Channel">
            <option value="sms_mock">SMS (mock)</option>
            <option value="email_mock">Email (mock)</option>
            <option value="webhook">Webhook</option>
          </select>
          <input value={rcpt} onChange={(e) => setRcpt(e.target.value)} placeholder="Recipient or webhook URL (optional)" />
        </div>
        <button className="alt" onClick={dispatch} disabled={!adv}>Send to authorities</button>
        <p className="note">{sent}</p>
      </aside>
      {data ? <HazardMap layers={data.h} /> : <div className="map" />}
    </div>
  );
}
